esphome:
  name: ih-wifi-water-sensor
  friendly_name: IH WiFi Water Sensor
  on_boot:
    priority: -100
    then:
      - light.turn_on: wifi_status
      - delay: 500ms
      - while:
          condition:
            not:
              wifi.connected
          then:
            - light.toggle: wifi_status
            - delay: 500ms
      - logger.log: "WiFi Connected!"
      - light.turn_on: wifi_status
      - logger.log: "Waiting for the API to connect..."
      - wait_until:
          condition:
            api.connected:
      - if:
          condition:
            api.connected:
          then:
            - logger.log: "API Connected"
          else:
            - logger.log: "API NOT Connected"  
      - logger.log: "I'm still in the on_boot code..."
      - delay: 5s
      
      - if:
          condition:
            binary_sensor.is_on: prevent_deep_sleep
          then:
            - deep_sleep.prevent: deep_sleep_1
            - logger.log: "Waiting for OTA Update..."
            - repeat:
                count: 150
                then:
                  - delay: 2s
            - script.execute: turnoff_ha_ota
            - logger.log: "Give up waiting on OTA..."
            - deep_sleep.allow: deep_sleep_1
          else:
            - component.update: bat_volts
            - logger.log: 'Entering Deep Sleep'
      - light.turn_off: wifi_status
      - deep_sleep.enter: deep_sleep_1
      
bk72xx:
  board: cbu
  framework:
    version: 0.0.0
    source: https://github.com/cap9qd/libretiny.git#master

# Enable logging
logger:
  baud_rate: 115200
  level: DEBUG
  hardware_uart: UART1

web_server:
  port: 80

captive_portal:

# Enable Home Assistant API
api:
  encryption:
    key: "mdpNNAkhq8oHz70F70BfDYPO7SMsU7j5ikGmXoNhpmg="

ota:
  password: "82f3fcc3db4d823f807f9115b79759f4"
  on_end:
    then:
      - script.execute: turnoff_ha_ota

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Sq400B-DBF891 Hotspot"
    password: "17jiH7OW8C4Q"

# Example configuration entry
binary_sensor:
  - platform: gpio
    pin:
      number: 20
      mode:
        input: true
        pullup: true
      inverted: true
    name: "RST Button"
    id: rst_button
    publish_initial_state: true
  - platform: gpio
    pin: 
      number: 16
      mode:
        input: true
        pullup: false
        pulldown: false
    name: "Leak Pin"
    id: leak_pin
    publish_initial_state: true
  - platform: gpio
    pin: 
      number: 7
    name: "BZ_PIN"
  - platform: homeassistant
    id: prevent_deep_sleep
    entity_id: input_boolean.watersensorota
    publish_initial_state: true     # This is important!
    
# Example configuration entry
output:
  - platform: gpio
    pin: 26
    id: status_led
  
sensor:
  - platform: adc
    pin: 23
    name: "Battery Voltage"
    id: bat_volts
    update_interval: never
    filters:
      - multiply: 2.0

deep_sleep:
#  sleep_duration: 60sec
#  run_duration: 60sec
  run_duration: 
    default: 60sec
    gpio_wakeup_reason: 60sec
  sleep_duration: 131076sec 
  #60min
  bk71xx_gpio_wakeup:
    - number: 16
      pin_mode: high_keep_awake
    - number: 20
      pin_mode: low_keep_awake
  id: deep_sleep_1
  
light:
  - platform: binary
    id: wifi_status
    output: status_led
    restore_mode: ALWAYS_ON

switch:
  - platform: restart
    name: "Restart"
  - platform: safe_mode
    name: "Restart (Safe Mode)"
  - platform: gpio
    pin: 
      number: 17
      mode: 
        output: true
    restore_mode: ALWAYS_ON
    id: samp_sw_pin
    name: SAMP_SW_PIN
    
script: 
  - id: turnoff_ha_ota
    then:
      - homeassistant.service:
          service: input_boolean.turn_off
          data:
            entity_id:
              input_boolean.watersensorota