esphome:
  name: sq400b-dbf891
  friendly_name: SQ400B DBF891
  on_boot:
    priority: 300
    then:
      - light.turn_on: wifi_status
      - delay: 500ms
      - while:
          condition:
            not:
              wifi.connected
          then:
            - light.toggle: wifi_status
            - delay: 500ms
      - light.turn_off: wifi_status
      
bk72xx:
  board: cb3s
  framework:
    version: 0.0.0
    source: https://github.com/cap9qd/libretiny.git#master

# Enable logging
logger:
  baud_rate: 115200
  level: DEBUG
  hardware_uart: UART1

web_server:
  port: 80

captive_portal:

# Enable Home Assistant API
api:
  encryption:
    key: "mdpNNAkhq8oHz70F70BfDYPO7SMsU7j5ikGmXoNhpmg="

ota:
  password: "82f3fcc3db4d823f807f9115b79759f4"

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
#    - ssid: CenturyLink4871-24G-4
#      password: 8jh3rc7zs3wr3k
#  manual_ip:
#    static_ip: 192.168.0.139
#    gateway: 192.168.0.1
#    subnet: 255.255.254.0
    
  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Sq400B-DBF891 Hotspot"
    password: "17jiH7OW8C4Q"

# Example configuration entry
#mqtt:
#  broker: 192.168.0.10
#  username: !secret mqtt_user
#  password: !secret mqtt_password

# Example configuration entry
binary_sensor:
#  - platform: gpio
#    pin:
#      number: 24
#      mode:
#        input: true
#        pullup: true
#      inverted: true
#    name: "RST Button"
#    id: rst_button
#  - platform: gpio
#    pin: 
#      number: 8
#      mode:
#        input: true
#        pullup: false
#        pulldown: false
#    name: "BASIC_PIN"
#    id: leak_pin
  - platform: gpio
    pin: 
      number: 6
      mode:
        input: true
        pullup: false
        pulldown: false
    name: "BZ_PIN"
  - platform: gpio
    pin: 14
    name: "SAMP_PIN"

# Example configuration entry
output:
  - platform: gpio
    pin: 26
    id: status_led
  - platform: gpio
    pin: 7
    id: buzzer

sensor:
  - platform: adc
    pin: 23
    name: "Battery Voltage"

deep_sleep:
  run_duration: 
    default: 30sec
    gpio_wakeup_reason: 30sec
  sleep_duration: 60min
  bk71xx_gpio_wakeup:
    - pin: 
        number: 8
        mode:
          input: true
          pullup: false
          pulldown: false
      pin_mode: high_keep_awake
    - pin:
        number: 24
        mode:
          input: true
          pullup: true
          pulldown: false
      pin_mode: low_keep_awake
  id: deep_sleep_1
  
light:
  - platform: binary
    id: wifi_status
    output: status_led
    restore_mode: ALWAYS_ON

switch:
  - platform: restart
    name: "Restart"
  - platform: safe_mode
    name: "Restart (Safe Mode)"
  - platform: template
    name: "Prevent DeepSleep"
    id: prevent_ds_sw
    optimistic: true
    restore_mode: always_off
    turn_on_action:
      - deep_sleep.prevent: deep_sleep_1
    turn_off_action:
      - deep_sleep.allow: deep_sleep_1
    on_turn_on:
      - delay: 2000ms
      - repeat:
          count: 60 # 60*2000ms = 2min
          then:
            - light.turn_on: wifi_status
            - delay: 100ms
            - light.turn_off: wifi_status
            - delay: 1900ms
      - switch.turn_off: prevent_ds_sw
