esphome:
  name: tuya-dev-blue
  on_boot:
    priority: -100
    then:
      - light.turn_on: wifi_status
      - delay: 500ms
      - while:
          condition:
            not:
              wifi.connected
          then:
            - light.toggle: wifi_status
            - delay: 500ms
      - logger.log: "WiFi Connected!"
      - light.turn_on: wifi_status
      - logger.log: "Waiting for the API to connect..."
      - wait_until:
          condition:
            api.connected:
      - if:
          condition:
            api.connected:
          then:
            - logger.log: "API Connected"
          else:
            - logger.log: "API NOT Connected"  
      
bk72xx:
  board: generic-bk7231n-qfn32-tuya
  framework:
    version: 0.0.0
    source: https://github.com/cap9qd/libretiny.git#feature/i2c-spi
logger:
  baud_rate: 115200
  level: VERY_VERBOSE
  hardware_uart: UART2

web_server:
  port: 80

captive_portal:

api:
  encryption:
    key: "mdpNNAkhq8oHz70F70BfDYPO7SMsU7j5ikGmXoNhpmg="

ota:
  password: "82f3fcc3db4d823f807f9115b79759f4"

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

  ap:
    ssid: "TuYa Dev Blue Hotspot"
    password: "17jiH7OW8C4Q"

binary_sensor:
  - platform: gpio
    pin:
      number: P9
      mode:
        input: true
        pullup: true
      inverted: true
    name: "RST Button"
    id: rst_button
    publish_initial_state: true
    
output:
  - platform: gpio
    pin: 16
    id: status_led
  
light:
  - platform: binary
    id: wifi_status
    output: status_led
    restore_mode: ALWAYS_ON

switch:
  - platform: restart
    name: "Restart"
  - platform: safe_mode
    name: "Restart (Safe Mode)"
  
i2c:
  sda: P22
  scl: P20
  scan: true
  id: bus_a
  
sensor:
  - platform: bmp085
    temperature:
      name: "Temperature"
    pressure:
      name: "Pressure"
    update_interval: 10s
