esphome:
  name: tuya-pir-alarm
  friendly_name: Tuya PIR Alarm 812WT
      
bk72xx:
  board: cbu
  framework:
    version: 0.0.0
    source: https://github.com/cap9qd/libretiny.git#master

# Enable logging
logger:
  baud_rate: 115200
  level: DEBUG
  hardware_uart: UART1

web_server:
  port: 80

captive_portal:

# Enable Home Assistant API
api:
  encryption:
    key: "gPCd8pqt4e+FnUQN4SmVGM8DViiYIpeqETn0AFmj/84="

ota:
  password: "82f3fcc3db4d823f807f9115b79759f4"

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Tuya PIR Hotspot"
    password: "17jiH7OW8C4Q"
    
button:
  - platform: restart
    name: Restart

debug:
  update_interval: 30s

text_sensor:
  - platform: debug
    reset_reason:
      name: Reset Reason

binary_sensor:
  - platform: gpio
    id: binary_switch_1
    pin:
      number: P14
      inverted: true
      mode: INPUT_PULLUP
  - platform: gpio
    id: pir_input
    name: PIR Input
    pin: 
      number: P22
      mode: INPUT_PULLUP
    on_press: 
      - switch.turn_on: status_led
    on_release: 
      - switch.turn_off: status_led

# Example configuration entry
output:
  - platform: libretiny_pwm
    pin: P6
    frequency: 10000 Hz
    id: pwm_output

light:
  - platform: monochromatic
    name: "Buzzer"
    output: pwm_output

switch:
  - platform: gpio
    name: RST Switch Pullup
    id: switch_pullup_out
    pin: P16
  - platform: gpio
    name: status_led
    id: status_led
    pin: 
      number: P20
      inverted: true

sensor:
  - platform: adc
    pin: P23
    name: "Battery Voltage"
    id: bat_volts
    update_interval: 10s
    filters:
      - multiply: 2.0
      